In [10]:
import pandas as pd
import io

dados_csv = """UF ; Salário inicial ; Região
MS ;13.007,12; Centro-Oeste
MA ;8.452,03; Nordeste
PA ;8.289,86; Norte
RR ;7.700,47; Norte
MT ;7.343,44; Centro-Oeste
PB ;6.944,09; Nordeste
RN ;6.814,88; Nordeste
AP ;6.600,98; Norte
DF ;6.427,71; Centro-Oeste
SE ;6.176,76; Nordeste
TO ;6.130,70; Norte
PE ;5.841,91; Nordeste
AL ;5.767,15; Nordeste
ES ;5.685,97; Sudeste
AM ;5.631,18; Norte
SP ;5.565,00; Sudeste
AC ;5.370,35; Norte
GO ;5.160,49; Centro-Oeste
RO ;5.118,41; Norte
RS ;5.111,05; Sul
SC ;5.026,80; Sul
PI ;4.984,17; Nordeste
BA ;4.965,24; Nordeste
CE ;4.961,73; Nordeste
PR ;4.920,55; Sul
MG ;4.867,97; Sudeste"""

df = pd.read_csv(io.StringIO(dados_csv), sep=';', decimal=',', thousands='.', skipinitialspace=True)

df.columns = df.columns.str.strip()
df['UF'] = df['UF'].str.strip()
df['Região'] = df['Região'].str.strip()

df.head()

   UF  Salário inicial        Região
0  MS         13007.12  Centro-Oeste
1  MA          8452.03      Nordeste
2  PA          8289.86         Norte
3  RR          7700.47         Norte
4  MT          7343.44  Centro-Oeste

In [14]:
estado_menor = df.loc[df['Salário inicial'].idxmin()]
estado_maior = df.loc[df['Salário inicial'].idxmax()]

print(f"MENOR salário: {estado_menor['UF']} (R$ {estado_menor['Salário inicial']:,.2f})")
print(f"MAIOR salário: {estado_maior['UF']} (R$ {estado_maior['Salário inicial']:,.2f})")

MENOR salário: MG (R$ 4,867.97)
MAIOR salário: MS (R$ 13,007.12)

In [18]:
df_rank = df.sort_values(by='Salário inicial', ascending=False).reset_index(drop=True)

posicao_go = df_rank[df_rank['UF'] == 'GO'].index[0] + 1

print(f"O estado de Goiás (GO) está na {posicao_go}ª posição.")

O estado de Goiás (GO) está na 18ª posição.

In [21]:
media_geral = df['Salário inicial'].mean()
print(f"Média salarial de TODOS os estados: R$ {media_geral:,.2f}")

Média salarial de TODOS os estados: R$ 6,264.08

In [25]:
tabela_regioes = df.groupby('Região')['Salário inicial'].agg(
    Média='mean',
    Maior='max',
    Menor='min'
).round(2)

tabela_regioes = tabela_regioes.sort_values(by='Média', ascending=False)

tabela_regioes

                Média     Maior    Menor
Região
Centro-Oeste  7984.69  13007.12  5160.49
Norte         6405.99   8289.86  5118.41
Nordeste      6100.88   8452.03  4961.73
Sudeste       5372.98   5685.97  4867.97
Sul           5019.47   5111.05  4920.55

In [32]:
regiao_maior_media = tabela_regioes['Média'].idxmax()
regiao_menor_media = tabela_regioes['Média'].idxmin()

print(f"Região com MAIOR média: {regiao_maior_media}")
print(f"Região com MENOR média: {regiao_menor_media}")

Região com MAIOR média: Centro-Oeste
Região com MENOR média: Sul