In [16]:
import pandas as pd

dados = {
    'UF': ['MS', 'MA', 'PA', 'RR', 'MT', 'PB', 'RN', 'AP', 'DF', 'SE', 'TO', 'PE', 'AL', 'ES', 'AM', 'SP', 'AC', 'GO', 'RO', 'RS', 'SC', 'PI', 'BA', 'CE', 'PR', 'MG'],
    'Salário inicial': [13007.12, 8452.03, 8289.86, 7700.47, 7343.44, 6944.09, 6814.88, 6600.98, 6427.71, 6176.76, 6130.70, 5841.91, 5767.15, 5685.97, 5631.18, 5565.00, 5370.35, 5160.49, 5118.41, 5111.05, 5026.80, 4984.17, 4965.24, 4961.73, 4920.55, 4867.07],
    'Região': ['Centro-Oeste', 'Nordeste', 'Norte', 'Norte', 'Centro-Oeste', 'Nordeste', 'Nordeste', 'Norte', 'Centro-Oeste', 'Nordeste', 'Norte', 'Nordeste', 'Nordeste', 'Sudeste', 'Norte', 'Sudeste', 'Norte', 'Centro-Oeste', 'Norte', 'Sul', 'Sul', 'Nordeste', 'Nordeste', 'Nordeste', 'Sul', 'Sudeste']
}

df = pd.DataFrame(dados)

df['UF'] = df['UF'].str.strip()
df['Região'] = df['Região'].str.strip()

df.head()

   UF  Salário inicial        Região
0  MS         13007.12  Centro-Oeste
1  MA          8452.03      Nordeste
2  PA          8289.86         Norte
3  RR          7700.47         Norte
4  MT          7343.44  Centro-Oeste

In [24]:
estado_menor = df.loc[df['Salário inicial'].idxmin()]
estado_maior = df.loc[df['Salário inicial'].idxmax()]

print(f"MENOR salário: {estado_menor['UF']} (R$ {estado_menor['Salário inicial']:,.2f})")
print(f"MAIOR salário: {estado_maior['UF']} (R$ {estado_maior['Salário inicial']:,.2f})")

MENOR salário: MG (R$ 4,867.07)
MAIOR salário: MS (R$ 13,007.12)

In [3]:
df_rank = df.sort_values(by='Salário inicial', ascending=False).reset_index(drop=True)

posicao_go = df_rank[df_rank['UF'] == 'GO'].index[0] + 1

print(f"O estado de Goiás (GO) está na {posicao_go}ª posição.")

O estado de Goiás (GO) está na 18ª posição.

In [32]:
media_geral = df['Salário inicial'].mean()
print(f"Média salarial de TODOS os estados: R$ {media_geral:,.2f}")

tabela_regioes = df.groupby('Região')['Salário inicial'].agg(
    Média='mean',
    Maior='max',
    Menor='min'
).round(2)

tabela_regioes = tabela_regioes.sort_values(by='Média', ascending=False)

tabela_regioes

Média salarial de TODOS os estados: R$ 6,264.04

                Média     Maior    Menor
Região
Centro-Oeste  7984.69  13007.12  5160.49
Norte         6405.99   8289.86  5118.41
Nordeste      6100.88   8452.03  4961.73
Sudeste       5372.68   5685.97  4867.07
Sul           5019.47   5111.05  4920.55

In [45]:
regiao_maior_media = tabela_regioes['Média'].idxmax()
regiao_menor_media = tabela_regioes['Média'].idxmin()

print(f"Região com MAIOR média: {regiao_maior_media}")
print(f"Região com MENOR média: {regiao_menor_media}")

Região com MAIOR média: Centro-Oeste
Região com MENOR média: Sul